# Site settings
title: Fernando Alves
email: fernandojfalves.536@gmail.com
url: https://github.com/noname536/portfolio/
description: "University of Copenhagen Computer Science Master Student"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Fernando Alves

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/fernandojfalves/
  - title: github
    url: https://github.com/noname536/portfolio/

# Build settings
markdown: kramdown
permalink: pretty
